### ISSUE TITLE
What is it?

### ISSUE THREAD

**Issue by kreuzerkrieg** [ttsiodras/straylight#1]
if (i_band <= 3) {
        AL_nb_detectors = 2.*tan(alpha_AL_max*M_PI/180.)*focal/VNIR_detector_size;
        AC_nb_detectors = 2.*tan(alpha_AC_max*M_PI/180.)*focal/VNIR_detector_size;
        AC_nb_detectors = IMGWIDTH;
    }

what do you mean by the second assignment to the AC_nb_detectors variable? Just discard the previous calculation?

**Comment by ttsiodras** [comment]
It's been many years since I wrote this code - but it looks like a copy-paste error from the `if` immediately following this section. There was no side-effect, because as you noticed yourself, the proper assignment followed immediately afterwards.

Committed a fix - thanks.
